export enum ComboType {
  BOMB_BOMB = 'BOMB_BOMB',
  LASER_LASER = 'LASER_LASER',
  DESTROY_DESTROY = 'DESTROY_DESTROY',
  DESTROY_BOMB = 'DESTROY_BOMB',
  LASER_BOMB = 'LASER_BOMB',
  DESTROY_LASER = 'DESTROY_LASER'
}
