import { config } from '../constants/config.js'
import { TYPECELL } from '../enums/TypeCell.js'
import { Attribute, Cell } from '../models/Cell.js'
const COLOR = config.COLOR.default
const COLOR_BORDER = config.COLOR.border

const attribute = new Attribute(COLOR, COLOR_BORDER)
const cell = (index: number, type: TYPECELL) => {
  return new Cell(index, type, false, false, false, attribute)
}

export function generateArrayCells() {
  const cells = [
    [
      cell(1, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(1, TYPECELL.BOOM),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(4, TYPECELL.BOOM),
      cell(1, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL)
    ],
    [
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL)
    ],
    [
      cell(3, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(0, TYPECELL.BOOM),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.VERTICAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL)
    ],
    [
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.BOOM),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(0, TYPECELL.BOOM),
      cell(0, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL)
    ],
    [
      cell(0, TYPECELL.NORMAL),
      cell(1, TYPECELL.VERTICAL),
      cell(0, TYPECELL.NORMAL),
      cell(0, TYPECELL.HORIZONTAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(1, TYPECELL.HORIZONTAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(1, TYPECELL.VERTICAL)
    ],
    [
      cell(2, TYPECELL.NORMAL),
      cell(0, TYPECELL.HORIZONTAL),
      cell(2, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.BOOM),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL)
    ],
    [
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.BOOM),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL)
    ],
    [
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(2, TYPECELL.VERTICAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL)
    ],
    [
      cell(0, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.BOOM),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.BOOM),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL)
    ],
    [
      cell(1, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL)
    ]
  ]
  return cells
}

export function generateArrayCellsDefault() {
  const cells = [
    [
      cell(0, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL)
    ],
    [
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL)
    ],
    [
      cell(3, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL)
    ],
    [
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL)
    ],
    [
      cell(0, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL)
    ],
    [
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL)
    ],
    [
      cell(3, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL)
    ],
    [
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL)
    ],
    [
      cell(0, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL)
    ],
    [
      cell(1, TYPECELL.NORMAL),
      cell(0, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL)
    ]
  ]
  return cells
}
