import { CellApi } from '../api/models/CellApi.js'
import { TYPECELL } from '../enums/TypeCell.js'

const cell = (index: number, type: TYPECELL) => {
  return new CellApi(type, index, false, false, false)
}

export function mockCellsAPIWithCombo() {
  const cells = [
    [
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.BOOM),
      cell(3, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(5, TYPECELL.NORMAL),
      cell(4, TYPECELL.BOOM),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL)
    ],
    [
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(5, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL)
    ],
    [
      cell(3, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.BOOM),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.VERTICAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(5, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL)
    ],
    [
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.BOOM),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(5, TYPECELL.BOOM),
      cell(5, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL)
    ],
    [
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.VERTICAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.HORIZONTAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.HORIZONTAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.VERTICAL)
    ],
    [
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.HORIZONTAL),
      cell(2, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.BOOM),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL)
    ],
    [
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.BOOM),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL)
    ],
    [
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.VERTICAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL)
    ],
    [
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.BOOM),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.BOOM),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL)
    ],
    [
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL)
    ]
  ]
  return cells
}

export function mockCellsAPIWithDefault() {
  const cells = [
    [
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(5, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL)
    ],
    [
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(5, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL)
    ],
    [
      cell(3, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(5, TYPECELL.NORMAL),
      cell(5, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL)
    ],
    [
      cell(4, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(5, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL)
    ],
    [
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(5, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(5, TYPECELL.NORMAL),
      cell(5, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL)
    ],
    [
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL)
    ],
    [
      cell(3, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(5, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(5, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL)
    ],
    [
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(5, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL)
    ],
    [
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL)
    ],
    [
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL)
    ]
  ]
  return cells
}
