import { CellApi } from '../api/models/CellApi.js'
import { config } from '../constants/config.js'
import { CellPosition } from '../core/main/CellPosition.js'
import { Attribute } from '../core/models/BaseCell.js'
import { BombCell } from '../core/models/BombCell.js'
import { DestroyCell } from '../core/models/DestroyCell.js'
import { NormalCell } from '../core/models/NormalCell.js'
import { TYPECELL } from '../enums/TypeCell.js'

const cell = (index: number, type: TYPECELL) => {
  return new CellApi(type, index, false, false, false)
}
const normalCell = (index: number) => {
  return new NormalCell(index, new Attribute(config.COLOR.default, config.COLOR.default))
}
const bombCell = (index: number, position: CellPosition) => {
  return new BombCell(index, position, new Attribute(config.COLOR.default, config.COLOR.default))
}
const destroyCell = (index: number, position: CellPosition) => {
  return new DestroyCell(index, position, new Attribute(config.COLOR.default, config.COLOR.default))
}
export function mockCellsAPIWithCombo() {
  const cells = [
    [
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.BOOM),
      cell(3, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.BOOM),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL)
    ],
    [
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL)
    ],
    [
      cell(3, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.BOOM),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.VERTICAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL)
    ],
    [
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.BOOM),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.BOOM),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL)
    ],
    [
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.VERTICAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.HORIZONTAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.HORIZONTAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.VERTICAL)
    ],
    [
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.HORIZONTAL),
      cell(2, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.BOOM),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL)
    ],
    [
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.BOOM),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL)
    ],
    [
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.VERTICAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL)
    ],
    [
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.BOOM),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.BOOM),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL)
    ],
    [
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL)
    ]
  ]
  return cells
}

export function mockCellsAPIWithDefault() {
  const cells = [
    [
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL)
    ],
    [
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL)
    ],
    [
      cell(3, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL)
    ],
    [
      cell(4, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL)
    ],
    [
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL)
    ],
    [
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL)
    ],
    [
      cell(3, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL)
    ],
    [
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL)
    ],
    [
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL)
    ],
    [
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(2, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(4, TYPECELL.NORMAL),
      cell(1, TYPECELL.NORMAL),
      cell(3, TYPECELL.NORMAL)
    ]
  ]
  return cells
}
export function mockBaseCellsAPIWithDefault() {
  const cells = [
    [
      /* 0 */
      bombCell(1, new CellPosition(0, 0)),
      destroyCell(6, new CellPosition(0, 1)),
      normalCell(1),
      normalCell(4),
      normalCell(2),
      normalCell(1),
      normalCell(1),
      normalCell(1),
      normalCell(3),
      normalCell(4),
      normalCell(3),
      normalCell(4),
      normalCell(1),
      normalCell(2),
      normalCell(1),
      normalCell(1),
      normalCell(2),
      normalCell(3)
    ],
    [
      /* 1 */ normalCell(2),
      normalCell(4),
      normalCell(2),
      normalCell(1),
      normalCell(4),
      normalCell(2),
      normalCell(1),
      normalCell(2),
      normalCell(4),
      normalCell(1),
      normalCell(2),
      normalCell(4),
      normalCell(1),
      normalCell(2),
      normalCell(4),
      normalCell(2),
      normalCell(4),
      normalCell(3)
    ],
    [
      /*2 */ normalCell(3),
      normalCell(4),
      normalCell(4),
      normalCell(1),
      normalCell(1),
      normalCell(2),
      normalCell(2),
      normalCell(3),
      normalCell(1),
      normalCell(3),
      normalCell(2),
      normalCell(1),
      normalCell(1),
      normalCell(1),
      normalCell(3),
      normalCell(1),
      normalCell(4),
      normalCell(2)
    ],
    [
      /* 3 */ normalCell(4),
      normalCell(4),
      normalCell(3),
      normalCell(2),
      normalCell(4),
      normalCell(1),
      normalCell(2),
      normalCell(1),
      normalCell(2),
      normalCell(1),
      normalCell(4),
      normalCell(1),
      normalCell(2),
      normalCell(1),
      normalCell(1),
      normalCell(2),
      normalCell(4),
      normalCell(1)
    ],
    [
      /* 4 */ normalCell(1),
      normalCell(4),
      normalCell(1),
      normalCell(1),
      normalCell(2),
      normalCell(4),
      normalCell(3),
      normalCell(1),
      normalCell(1),
      normalCell(1),
      normalCell(1),
      normalCell(1),
      normalCell(2),
      normalCell(1),
      normalCell(1),
      normalCell(2),
      normalCell(4),
      normalCell(1)
    ],
    [
      /* 5 */ normalCell(2),
      normalCell(3),
      normalCell(3),
      normalCell(2),
      normalCell(1),
      normalCell(2),
      normalCell(1),
      normalCell(2),
      normalCell(2),
      normalCell(1),
      normalCell(4),
      normalCell(2),
      normalCell(1),
      normalCell(3),
      normalCell(2),
      normalCell(1),
      normalCell(3),
      normalCell(4)
    ],
    [
      /* 6 */ normalCell(3),
      normalCell(3),
      normalCell(3),
      normalCell(2),
      normalCell(3),
      normalCell(3),
      normalCell(2),
      normalCell(1),
      normalCell(3),
      normalCell(1),
      normalCell(4),
      normalCell(2),
      normalCell(5),
      normalCell(3),
      normalCell(2),
      normalCell(4),
      normalCell(3),
      normalCell(4)
    ],
    [
      /* 7 */ normalCell(4),
      normalCell(3),
      normalCell(2),
      normalCell(1),
      normalCell(2),
      normalCell(1),
      normalCell(2),
      normalCell(2),
      normalCell(1),
      normalCell(2),
      normalCell(1),
      normalCell(1),
      normalCell(2),
      normalCell(2),
      normalCell(1),
      normalCell(1),
      normalCell(2),
      normalCell(3)
    ],
    [
      /* 8 */ normalCell(1),
      normalCell(4),
      normalCell(2),
      normalCell(1),
      normalCell(3),
      normalCell(2),
      normalCell(1),
      normalCell(3),
      normalCell(2),
      normalCell(1),
      normalCell(1),
      normalCell(2),
      normalCell(1),
      normalCell(1),
      normalCell(4),
      normalCell(3),
      normalCell(1),
      normalCell(3)
    ],
    [
      /* 9 */ normalCell(1),
      normalCell(2),
      normalCell(2),
      normalCell(3),
      normalCell(1),
      normalCell(4),
      normalCell(5),
      normalCell(2),
      normalCell(4),
      normalCell(3),
      normalCell(1),
      normalCell(4),
      normalCell(2),
      normalCell(2),
      normalCell(4),
      normalCell(4),
      normalCell(3),
      normalCell(3)
    ]
  ]
  return cells
}
